spring:
  config:
    activate:
      on-profile: local

  # WebClient 사용 시 메모리 버퍼사이즈 조절
  codec:
    max-in-memory-size: 10MB

  sql:
    init:
      mode: always # boot 실행 될 때마다 sql 스크립트 실행 - 나중에 시간 되면 추가

  # DB 사용 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory
    username: sjchoi
    password: SJchoi0504*
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 2
      max-lifetime: 55000
      auto-commit: false
      connection-test-query: SELECT 1
#      data: classpath:database/import.sql

#    data:
#      redis:
#        host: localhost
#        port: 6379

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        # 해당 내용은 hibernate로 자동 테이블 생성될때 같이 sql을 실행한다.
        hbm2ddl:
          import_files: classpath:database/import.sql
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        format_sql: true
        highlight_sql: true
        show_sql: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: C:${file.separator}logs${file.separator}logging.log
  level:
#    root: INFO
    com.zaxxer.hikari: info #HikariCP log 설정
    jdbc:
      audit: off # ResultSet을 제외한 JDBC호출 정보를 로그로 남긴다.
      resultset: off # ResultSet을 포함한 JDBC호출 정보를 로그로 남긴다.
      resultsettable: info # # SQL결과를 테이블 형태로 보여준다.
      sqltiming: info
      connection: info
    org:
      hibernate:
        sql: debug
        type: trace
      springframework.web: info
    javax.sql.DataSource: info
    log4jdbc.log4j2: off
